name: Build GUI exe with Pyinstaller

on: [push]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        # Directory containing source code (optional requirements.txt).
        path: . # default is src
    - uses: actions/upload-artifact@v3
      with:
        name: text-adventure
        path: dist/windows
    - uses: ColinPitrat/update-release@v1.0.1
      with:
        token: ${{ github.token }}
        files: dist/windows/text-adventure.zip

          
