name: Build GUI exe with Pyinstaller

on: [push]
jobs:
  Python:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $(git ls-files 'requirements.txt')
    - name: Analysing the code with pylint
      run: |
        python $(git ls-files '*.py') debug
  win_linux:
    needs: Python
    name: Comple Windows and Linux Binaries
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        # Directory containing source code (optional requirements.txt).
        path: . # default is src
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: text-adventure
        path: dist/windows
    - name: View Files
      run: cd dist/windows/main && zip win.zip * 
      
    - name: Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        file: "dist\\windows\\main\\win.zip"
        tags: false
        draft: false

          
