name: Build GUI exe with Pyinstaller

on: [push]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        # Directory containing source code (optional requirements.txt).
        path: . # default is src
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: text-adventure
        path: dist/windows
    - name: Zip folder
      run: pwd && zip -r text-adventure-win.zip dist/windows/main 
    - name: Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        file: "dist\\windows\\main\\text-adventure-win.zip"
        tags: false
        draft: false

          
