name: Building workflow

on: [push]
env:
  ID: $(git rev-parse --short "$GITHUB_SHA")
jobs:
  
  Python:
    runs-on: ubuntu-latest
    steps:
    - name: Show Run ID
      run: echo ${{ env.ID }}

    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $(git ls-files 'requirements.txt')
    - name: Run code with debug statement
      run: |
        python $(git ls-files '*.py') debug
  win_linux:
    needs: Python
    name: Comple Windows and Linux Binaries
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        # Directory containing source code (optional requirements.txt).
        path: . # default is src
    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v3
      with:
        name: text-adventure-win
        path: dist/windows
    - name: Build Linux
      # You may pin to the exact commit or the version.
      # uses: JackMcKew/pyinstaller-action-linux@38639c352a36917eea765f9283bfd1092c28af7b
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with:
        # Directory containing source code & .spec file (optional requirements.txt).
        path: .
    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v3
      with:
        name: text-adventure-linux
        path: dist/linux
    - name: Copy Necessary Files
      run: cp ./save.json dist/windows/main && cp ./save.json dist/linux/main
    - name: Zip Windows
      run: cd dist/windows/main && zip win-${{ env.sha_short }}.zip * 
    - name: Zip Linux
      run: cd dist/linux/main && zip linux-${{ env.sha_short }}.zip * 
    - name: Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        file: "dist\\windows\\main\\win-${{ env.ID }}.zip;dist\\linux\\main\\linux-${{ env.sha_short }}.zip"
        tags: false
        draft: false

          
